"""create water accounting zones table

Revision ID: 67f3d7e90039
Revises: d2e92f26bce6
Create Date: 2026-07-19 09:22:36.194429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67f3d7e90039'
down_revision: Union[str, Sequence[str], None] = 'd2e92f26bce6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('water_accounting_zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.Column('parent_zone_id', sa.Integer(), nullable=True),
    sa.Column('zone_code', sa.String(length=30), nullable=False),
    sa.Column('zone_name', sa.String(length=150), nullable=False),
    sa.Column('zone_type', sa.String(length=50), nullable=False),
    sa.Column('audit_boundary_description', sa.Text(), nullable=True),
    sa.Column('process_description', sa.Text(), nullable=True),
    sa.Column('elevation_m', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('design_water_demand_m3_day', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('baseline_start_date', sa.Date(), nullable=True),
    sa.Column('baseline_end_date', sa.Date(), nullable=True),
    sa.Column('baseline_consumption_m3', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('water_balance_frequency', sa.String(length=30), server_default='MONTHLY', nullable=False),
    sa.Column('metering_coverage_percent', sa.Numeric(precision=5, scale=2), server_default='0.00', nullable=False),
    sa.Column('audit_tolerance_percent', sa.Numeric(precision=5, scale=2), server_default='5.00', nullable=False),
    sa.Column('responsible_person', sa.String(length=150), nullable=True),
    sa.Column('cost_center', sa.String(length=50), nullable=True),
    sa.Column('is_audit_boundary', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('is_hydraulic_zone', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('audit_tolerance_percent >= 0 AND audit_tolerance_percent <= 100', name='ck_waz_audit_tolerance_range'),
    sa.CheckConstraint('baseline_consumption_m3 IS NULL OR baseline_consumption_m3 >= 0', name='ck_waz_baseline_consumption_nonnegative'),
    sa.CheckConstraint('baseline_end_date IS NULL OR baseline_start_date IS NULL OR baseline_end_date >= baseline_start_date', name='ck_waz_baseline_date_order'),
    sa.CheckConstraint('design_water_demand_m3_day IS NULL OR design_water_demand_m3_day >= 0', name='ck_waz_design_demand_nonnegative'),
    sa.CheckConstraint('metering_coverage_percent >= 0 AND metering_coverage_percent <= 100', name='ck_waz_metering_coverage_range'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_zone_id'], ['water_accounting_zones.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plant_id', 'zone_code', name='uq_water_accounting_zones_plant_code')
    )
    op.create_index(op.f('ix_water_accounting_zones_id'), 'water_accounting_zones', ['id'], unique=False)
    op.create_index(op.f('ix_water_accounting_zones_is_active'), 'water_accounting_zones', ['is_active'], unique=False)
    op.create_index(op.f('ix_water_accounting_zones_is_audit_boundary'), 'water_accounting_zones', ['is_audit_boundary'], unique=False)
    op.create_index(op.f('ix_water_accounting_zones_is_hydraulic_zone'), 'water_accounting_zones', ['is_hydraulic_zone'], unique=False)
    op.create_index(op.f('ix_water_accounting_zones_organization_id'), 'water_accounting_zones', ['organization_id'], unique=False)
    op.create_index(op.f('ix_water_accounting_zones_parent_zone_id'), 'water_accounting_zones', ['parent_zone_id'], unique=False)
    op.create_index(op.f('ix_water_accounting_zones_plant_id'), 'water_accounting_zones', ['plant_id'], unique=False)
    op.create_index(op.f('ix_water_accounting_zones_zone_code'), 'water_accounting_zones', ['zone_code'], unique=False)
    op.create_index(op.f('ix_water_accounting_zones_zone_name'), 'water_accounting_zones', ['zone_name'], unique=False)
    op.create_index(op.f('ix_water_accounting_zones_zone_type'), 'water_accounting_zones', ['zone_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_water_accounting_zones_zone_type'), table_name='water_accounting_zones')
    op.drop_index(op.f('ix_water_accounting_zones_zone_name'), table_name='water_accounting_zones')
    op.drop_index(op.f('ix_water_accounting_zones_zone_code'), table_name='water_accounting_zones')
    op.drop_index(op.f('ix_water_accounting_zones_plant_id'), table_name='water_accounting_zones')
    op.drop_index(op.f('ix_water_accounting_zones_parent_zone_id'), table_name='water_accounting_zones')
    op.drop_index(op.f('ix_water_accounting_zones_organization_id'), table_name='water_accounting_zones')
    op.drop_index(op.f('ix_water_accounting_zones_is_hydraulic_zone'), table_name='water_accounting_zones')
    op.drop_index(op.f('ix_water_accounting_zones_is_audit_boundary'), table_name='water_accounting_zones')
    op.drop_index(op.f('ix_water_accounting_zones_is_active'), table_name='water_accounting_zones')
    op.drop_index(op.f('ix_water_accounting_zones_id'), table_name='water_accounting_zones')
    op.drop_table('water_accounting_zones')
    # ### end Alembic commands ###
