"""create plants table

Revision ID: d2e92f26bce6
Revises: c1444267cc45
Create Date: 2026-07-15 15:31:35.957721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2e92f26bce6'
down_revision: Union[str, Sequence[str], None] = 'c1444267cc45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('plant_code', sa.String(length=30), nullable=False),
    sa.Column('plant_name', sa.String(length=150), nullable=False),
    sa.Column('plant_type', sa.String(length=100), nullable=True),
    sa.Column('address_line_1', sa.String(length=255), nullable=True),
    sa.Column('address_line_2', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=100), server_default='India', nullable=False),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('timezone', sa.String(length=50), server_default='Asia/Kolkata', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'plant_code', name='uq_plants_organization_code')
    )
    op.create_index(op.f('ix_plants_id'), 'plants', ['id'], unique=False)
    op.create_index(op.f('ix_plants_is_active'), 'plants', ['is_active'], unique=False)
    op.create_index(op.f('ix_plants_organization_id'), 'plants', ['organization_id'], unique=False)
    op.create_index(op.f('ix_plants_plant_code'), 'plants', ['plant_code'], unique=False)
    op.create_index(op.f('ix_plants_plant_name'), 'plants', ['plant_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plants_plant_name'), table_name='plants')
    op.drop_index(op.f('ix_plants_plant_code'), table_name='plants')
    op.drop_index(op.f('ix_plants_organization_id'), table_name='plants')
    op.drop_index(op.f('ix_plants_is_active'), table_name='plants')
    op.drop_index(op.f('ix_plants_id'), table_name='plants')
    op.drop_table('plants')
    # ### end Alembic commands ###
